# Generated by Django 5.2.16 on 2026-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number']},
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='List of amenities'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, help_text='Display name for the room', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.8, help_text='Guest rating', max_digits=3),
        ),
        migrations.AddField(
            model_name='room',
            name='review_count',
            field=models.IntegerField(default=0, help_text='Number of reviews'),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.IntegerField(default=30, help_text='Room size in square meters'),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('executive', 'Executive'), ('presidential', 'Presidential')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('reserved', 'Reserved')], default='available', max_length=20),
        ),
    ]
