# Generated by Django 4.2 on 2026-10-06 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_alter_room_options_room_amenities_room_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_username', models.CharField(max_length=150)),
                ('actor_role', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('CHECKIN_CODE_GENERATED', 'Check-in Access Code Generated'), ('ACCESS_CODE_VERIFIED', 'Access Code Verified'), ('EMERGENCY_CODE_GENERATED', 'Emergency 1-Hour Code Generated'), ('CLEANING_CODE_REQUESTED', 'Cleaning Access Code Requested'), ('CLEANING_CODE_APPROVED', 'Cleaning Access Code Approved'), ('CLEANING_CODE_REJECTED', 'Cleaning Access Code Rejected'), ('ROOM_CLEANED_ACTIVATED', 'Room Cleaned & Activated to Available'), ('ROOM_STATUS_CHANGED', 'Room Status Changed'), ('ACCESS_CODE_REVOKED', 'Access Code Revoked')], db_index=True, max_length=60)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=50)),
                ('access_code', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to='bookings.booking')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to='rooms.room')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RoomAccessCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('code_type', models.CharField(choices=[('checkin', 'Check-in Guest Access'), ('emergency', 'Emergency Override (1 Hour)'), ('cleaning', 'Housekeeping Cleaning Access')], max_length=20)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Manager Approval'), ('active', 'Active'), ('expired', 'Expired'), ('used', 'Used / Completed'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_access_codes', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_codes', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_codes', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
