# Generated by Django 4.2 on 2026-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('BAR_STAFF', 'Bar Staff'), ('HOUSEKEEPING', 'Housekeeping'), ('ADMIN', 'Admin')], default='RECEPTIONIST', max_length=20),
        ),
    ]
