# Generated by Django 5.2.16 on 2026-08-02 02:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.CharField(help_text='Display number (e.g., 1, 2, 3 or A1, B2)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Friendly name (e.g., Garden View, Window Seat)', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name (e.g., garden-view)', max_length=100, unique=True)),
                ('capacity', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('qr_code', models.TextField(blank=True, help_text='Base64 QR code image', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.CharField(blank=True, help_text='e.g., Indoor, Outdoor, VIP', max_length=100, null=True)),
                ('floor', models.CharField(blank=True, help_text='e.g., Ground, First, Second', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_restaurant_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tables',
                'ordering': ['table_number'],
            },
        ),
    ]
