# Generated by Django 4.2 on 2026-08-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('korapay', 'Korapay'), ('bank_transfer', 'Bank Transfer'), ('room_charge', 'Room Charge')], max_length=20),
        ),
    ]
